### ISSUE TITLE
Service Shell

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/stamp#6]
Empty service with required build pilelines, etc...

```[tasklist]
### Tasks
- [x] Create service and test projects
- [x] Create docker file
- [x] create make file
- [x] create chart?
- [x] add workflows
```
